### ISSUE TITLE
Refactor logic where enums are used

### ISSUE THREAD

**Issue by myssto** [osu-tournament-rating/otr-api#234]
EF has the ability to handle casting enums to their integer values, so wherever an entity holds an integer representation of an enum, we should prefer using the enum as the property's type instead of `int`. For example, in `Entities.Game` the property `VerificationStatus` is typed as an `int?` where it could be `MatchVerificationStatus?`.

In addition, we should be using the enums for comparisons instead of literals. For example, in `Utilities.QueryExtensions` the function `IQueryable<Game> WhereVerified` uses the comparison `.Where(x => x.VerificationStatus == (int)GameVerificationStatus.Verified && x.RejectionReason == null);`. Using the above rationale, this comparison could just use the enum value without casting to `int`.

Finally, where functions take integer casts of enums, we should require passing the enum instead. If any integer casting should need to be done, it should be the responsibility of the function instead, not the function from where it is called. For example, consider the method `MatchesService.CreateAsync()`. In this definition, instead of taking an `int? verificationSource`, the method should take a `MatchVerificationSource? verificationSource`.

```cs
    /// <summary>
    /// Creates matches
    /// </summary>
    /// <param name="tournamentId">Id of the parent tournament</param>
    /// <param name="submitterId">Id of the submitting user</param>
    /// <param name="matchIds">List of match ids</param>
    /// <param name="verify">Submitter is a match verifier</param>
    /// <param name="verificationSource">Source of verification (int representation of <see cref="MatchVerificationSource"/></param>
    /// <returns>Location information for the created matches, or null if parent tournament does not exist</returns>
    Task<IEnumerable<MatchCreatedResultDTO>?> CreateAsync(
        int tournamentId,
        int submitterId,
        IEnumerable<long> matchIds,
        bool verify,
        int? verificationSource
        );
```

Tasks
- [ ] Refactor entities to use enums over integer castings of enums
- [ ] Refactor comparisons and queries to use enums over integer castings of enums
- [ ] Refactor method parameters to take enums over integer castings of enums

**Comment by hburn7** [comment]
I think we've done this.
