### ISSUE TITLE
Use pagination instead of `/matches/convert`

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#308]
Instead of using `/matches/convert` we should use pagination, such as `/matches?limit=[var]&offset=[var] GET`.

This behavior is a breaking change for the `otr-processor`.

## Tasks

- [x] Remove the `/matches/convert` endpoint
- [x] Remove the `/matches/ids` endpoint
- [x] Remove the `/matches/id-mapping` endpoint (used by `otr-processor` but only in a test function afaik, not actually used for anything).
- [x] Implement optional pagination parameters for `/matches GET`: `limit` and `offset`.
- [x] Ensure this endpoint returns all navigation fields in the response.
