### ISSUE TITLE
Migrate data processing functions to microservice

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#324]
# Migrate data processing to microservice

The o!TR API should not be the program doing all of the API calls & automation checks. We want the API to be...an API. Not an API, data processor, and data sanitizer.

# Steps

## Documentation

- [x] Thoroughly document all of the processes which will live in the new microservice.
- [x] Document all of the states by which the new automation workflows will behave
- [x] Document and rearchitect the relevant database tables (tournaments, matches, games, match_scores)

## Code changes (API)

- [x] Rewrite & redocument all of the `VerificationStatus` enums
- [x] Rewrite & redocument all of the `RejectionReason` enums
- [x] Add new `ProcessingStatus` enums for `Match` and `Tournament`
- [x] Incorporate new `RejectionReason` and `VerificationStatus` fields to entities that need them.
- [x] Rewrite `Tournament` submission flow (intention to verify)

## Code migration

- [x] Create new .NET project for database-related classes.
- [x] Migrate all repositories and repository interfaces to the new database project.
- [x] Create new .NET project under the same solution for the data worker. This will be a .NET console app that runs until killed. Reference the 'Database' project
- [x] Implement `NeedsData` flow
- [x] Implement `NeedsAutomationChecks (Match)` flow
- [x] Implement `NeedsAutomationChecks (Tournament)` flow
- [x] Implement `Player` data fetch flow

## Tests

- [x] Test `NeedsData` flow
- [x] Test `NeedsAutomationChecks (Match)` flow
- [x] Test `NeedsAutomationChecks (Tournament)` flow
- [x] Test `Player` data fetch flow
  - [x] osu! API
  - [x] osu!track API

## API Cleanup

- [x] Remove migrated API credentials from the `example.appsettings.json` file (and the actions secrets, config classes, etc)
- [x] Remove `OsuPlayerDataWorker`
- [x] Remove `OsuMatchDataWorker`
- [x] Remove `MatchDuplicateDataWorker`
- [x] Remove `OsutrackApiWorker`
- [x] Remove `AutomationChecksUtils`
- [x] Remove `MatchAutomationChecks`
- [x] Remove `GameAutomationChecks`
- [x] Remove `AutomationChecksTests`
- [x] Resolve any conflicts
