### ISSUE TITLE
New statistics processing inside data worker microservice

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#332]
Depends on:

- [x] Some known tournaments are verified
- [x] Ratings are generated for these tournaments

Tasks:

- [x] Implement new statistics flow
- [x] Statistics flow completes for these items
