### ISSUE TITLE
Accept `ICollection<long>? beatmapIds` in tournament submission

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#437]
# Overview

Users should be able to submit a collection of beatmap ids when submitting a tournament.

# Tasks

- [ ] Add `public IEnumerable<long> BeatmapIds { get; set; } = new List<long>();` to `TournamentDTO`
- [ ] Document new DTO field
- [ ] In the submission endpoint, ensure any values `< 1` are removed.
