### ISSUE TITLE
Registered users over time

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#460]
# Overview

High level objective is to model the number of registered users over time. This is simply displaying a collection of time-series data.

1. Write a database query that groups number of users by signup date (per day)
2. Write a `TimeSeriesDataPointDTO` (if it doesn't exist) which maps this query result into a structure like `object Y, DateTime X`.
3. Write a controller & service layer

# Tasks
- [ ] Create db query under the `UserRepository` @myssto *if you think this should be in a `StatsRepository` instead let me know.*
- [ ] Create `StatisticsService` class (if it doesn't exist) with a method which maps the results to a collection of DTOs, i.e. `ICollection<TimeSeriesDataPointDTO>`
- [ ] Create `/api/v1/stats/registered-users` route which returns

**Comment by myssto** [comment]
I think before we implement anything for the global stats page we should revisit caching. These will be expensive queries that will evaluate over entire tables and we shouldn't run them on every request. They should be cached with a long lifetime

**Comment by hburn7** [comment]
Could easily be cached on a 24-hour timer
