### ISSUE TITLE
Provide data for `Game` page

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#496]
- Depends on #371, #332, #504
- Depends on having statistics in the database / after some data has been verified

# Overview

- Create all data needed for the dedicated Game page on the site

# Tasks

- [ ] Create `GameCompactDTO` which has game data without any navigations
- [ ] Create `GameResultDTO` which contains `teamRedScore: int` and `teamBlueScore: int` and include on `GameDTO`
- [ ] Create `GameMatchInfoDTO` which contains `totalGames: int` and `matchWinner: str` and include on `GameDTO`
- [ ] Include `TournamentCompactDTO` and include on `GameDTO`
- [ ] Include `BeatmapDTO` on `GameDTO`
  - [ ] If not present, include a `thumbnailUrl` field on `BeatmapDTO` which polls the osu! website for the beatmap image
  - Should we store thumbnails on our side or can we dynamically call this?
- [ ] Create `GameTeamStatisticsDTO` which has `averageScore`, `averageMisses`, `averageAccuracy`, and `averageRating` of those who participated in the game. There should be one of these DTOs included for team red and team blue (i.e. `game.teamRedStatistics.averageScore`.
  - The rating values displayed should be the player ratings at the time this match occurred. This can be found by querying for the `RatingAdjustment` which happened immediately prior to the match's `StartTime`.

# Design
![image](https://github.com/user-attachments/assets/7f3befe6-7c0f-4889-95d8-c89ae77a40a4)

**Comment by hburn7** [comment]
Replaced by #580
