### ISSUE TITLE
Provide data for `Match` page

### ISSUE THREAD

**Issue by hburn7** [osu-tournament-rating/otr-api#504]
Depends on:
- #332 (and stats being available in the database)

# Overview

Each match has a dedicated page. We need to provide the data for the frontend to display this page.

# Design

This is all we need for beta, we can expand on it later.

![image](https://github.com/user-attachments/assets/e3d384d3-4306-4b4d-98f7-b5a0a4f41a76)

# Implementation

- [ ] Create a `MatchCompactDTO` with the basic fields of a standalone match (e.g. no / minimal navigations)
- [ ] Include `TournamentCompactDTO` on `MatchDTO`
- [ ] Create `GameResultThumbnailDTO` with the following fields:
  - [ ] `backgroundUrl: str` - Link to the beatmap background url (low res)
  - [ ] `winner: Database.Enums.Team` - The identifier of who won the match
  - [ ] `beatmapUrl: str` - Link to the beatmap (osu!)
  - [ ] `beatmapId: int` - The o!TR id of the beatmap 
- [ ] Create `PlayerRatingChangeDTO` with the following fields:
  - [ ] `playerId: int` - The o!TR id of the player
  - [ ] `username: str` - The player username
  - [ ] `oldRating: double` - The rating of the player immediately before this match
  - [ ] `newRating: double` - The rating of the player immediately after this match
- [ ] Create `MatchRatingChangesDTO` with the following fields:
  - [ ] `teamRed: ICollection<PlayerRatingChangeDTO>` - One item per player on team red
  - [ ] `teamBlue: ICollection<PlayerRatingChangeDTO>` - One item per player on team blue
- [ ] Create `MatchTeamStatisticsDTO` with the following fields:
  - [ ] `averageScore: double` - The average score across the whole match for a team
  - [ ] `averageMisses: double` - The average number of misses across the whole match for a team
  - [ ] `averageAccuracy: double` - The average accuracy across the whole match for a team
- [ ] Implement database service / repository layers as needed to ensure statistics are gathered as described here.

**Comment by hburn7** [comment]
Replaced by #580
